version: "3.7"

services:
  client:
    volumes:
      - ./client/build:/usr/share/nginx/html/

  application:
    volumes:
      - ./application:/home/app
      - /home/app/node_modules
    command: ["npm", "run", "dev"]

  gateway:
    volumes:
      - /home/app/gateway/node_modules
      - ./gateway/:/home/app/gateway
    command: ["npm", "run", "dev"]
    ports:
      # Expose graphql-playground localhost:4000
      - "4000:80"

  cms:
    volumes:
      - /home/app/server/node_modules
      - ./cms/:/home/app/server

  processor:
    volumes:
      - ./processor/src/app:/app/app
    ports:
      - "1000:80"

  enrichment:
    ports:
      - "5000:5000"

  processor_db:
    ports:
      - '27017:27017'
